version: '3'
services:
  db:
    image: postgres:11
    ports:
      - "65432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ~/fastApiProject/postgres_data:/var/lib/postgresql/data
